### ISSUE TITLE
关于str.isalnum的疑问

### ISSUE THREAD

**Issue by pxn626** [zhukeyi123/Python_Work#1]
你好 我下载了你的源码 自学看到 def search 里面的一句代码
str.isalnum(keyword)==False
我查了网上的资料都说这个没有参数，是你写错了还是python更新了
还是什么 望解答

**Comment by pigzzz104** [comment]
https://m.runoob.com/python/att-string-isalnum.html
这里的keyword可以换成你自己的变量
发自我的iPad

> 在 2020年3月16日，21:20，pxn626 <notifications@github.com> 写道：
> 
> str.isalnum
