### ISSUE TITLE
关于打包为 exe

### ISSUE THREAD

**Issue by guyian** [zhukeyi123/Python_Work#3]

**Comment by guyian** [comment]
请问是使用 哪个模块进行打包的?
我使用 pyinstaller 打包不能运行

**Comment by pigzzz104** [comment]
我上次用pyinstaller打包可以运行，我这次更新打包发现又不能运行了，我也不知道为什么。

你可以录屏一下，查看闪退原因。
估计是模块没装全

**Comment by guyian** [comment]
我也是, 换个版本打包体积就不一样了, 难玩
